const express = require('express');
const router = express.Router();
const { SchedulerModel, VideoModel } = require('../models');
const { v4: uuidv4 } = require('uuid');

/**
 * Scheduler Routes
 * CRUD operations for schedulers
 */

// Helper: Generate human-readable scheduler name
function generateSchedulerName() {
    const adjectives = ['Melodic', 'Rhythmic', 'Harmonic', 'Sonic', 'Vibrant', 'Cosmic', 'Electric', 'Sunset', 'Morning', 'Midnight'];
    const nouns = ['Vibes', 'Beats', 'Waves', 'Dreams', 'Journey', 'Sessions', 'Mix', 'Studio', 'House', 'Flow'];

    const adj = adjectives[Math.floor(Math.random() * adjectives.length)];
    const noun = nouns[Math.floor(Math.random() * nouns.length)];

    return `${adj} ${noun}`;
}

// Helper: Calculate next run time
function calculateNextRun(time, frequency, activeDays) {
    const now = new Date();
    const [hours, minutes] = time.split(':').map(Number);

    const next = new Date(now);
    next.setHours(hours, minutes, 0, 0);

    // If time has passed today, start from tomorrow
    if (next <= now) {
        next.setDate(next.getDate() + 1);
    }

    // For weekly, adjust to next active day
    if (frequency === 'weekly' && activeDays && activeDays.length > 0) {
        while (!activeDays.includes(next.getDay())) {
            next.setDate(next.getDate() + 1);
        }
    }

    return next.toISOString();
}

/**
 * GET /api/schedulers
 * List all schedulers for user
 */
router.get('/', async (req, res) => {
    const { userId, channelId } = req.query;

    if (!userId) {
        return res.status(400).json({ error: 'userId required' });
    }

    try {
        const schedulers = await SchedulerModel.findByUser(userId, channelId);
        res.json({ schedulers });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

/**
 * POST /api/schedulers
 * Create new scheduler
 */
router.post('/', async (req, res) => {
    const {
        userId,
        channelId,
        time,
        frequency,
        activeDays,
        language,
        genres,
        titlePrompt,
        descPrompt,
        tagsPrompt,
        lyricsPrompt
    } = req.body;

    // Validation
    if (!userId || !channelId || !time || !frequency || !language || !genres || genres.length === 0) {
        return res.status(400).json({ error: 'Missing required fields' });
    }

    try {
        const scheduler = await SchedulerModel.createScheduler({
            name: generateSchedulerName(),
            userId,
            channelId,
            time,
            frequency,
            activeDays: activeDays || [],
            language,
            genres,
            titlePrompt: titlePrompt || '',
            descPrompt: descPrompt || '',
            tagsPrompt: tagsPrompt || '',
            lyricsPrompt: lyricsPrompt || '',
            nextRunAt: calculateNextRun(time, frequency, activeDays)
        });

        console.log(`[Schedulers] ✅ Created scheduler: ${scheduler.name}`);

        // Trigger immediate generation for the first video
        const videoWorker = req.app.get('videoWorker');
        if (videoWorker) {
            videoWorker.triggerForScheduler(scheduler.id);
        }

        res.status(201).json({ scheduler });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

/**
 * GET /api/schedulers/:id
 * Get scheduler details
 */
router.get('/:id', async (req, res) => {
    const { id } = req.params;

    try {
        const scheduler = await SchedulerModel.findById(id);

        if (!scheduler) {
            return res.status(404).json({ error: 'Scheduler not found' });
        }

        // Get recent videos generated by this scheduler
        const recentVideos = await VideoModel.findByScheduler(id, 10);

        res.json({ scheduler, recentVideos });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

/**
 * PATCH /api/schedulers/:id
 * Update scheduler (only editable fields)
 */
router.patch('/:id', async (req, res) => {
    const { id } = req.params;
    const { genres, titlePrompt, descPrompt, tagsPrompt, lyricsPrompt } = req.body;

    try {
        const scheduler = await SchedulerModel.findById(id);

        if (!scheduler) {
            return res.status(404).json({ error: 'Scheduler not found' });
        }

        // Only update editable fields (immutable: time, frequency, activeDays, language)
        const updates = {};
        if (genres) updates.genres = genres;
        if (titlePrompt !== undefined) updates.titlePrompt = titlePrompt;
        if (descPrompt !== undefined) updates.descPrompt = descPrompt;
        if (tagsPrompt !== undefined) updates.tagsPrompt = tagsPrompt;
        if (lyricsPrompt !== undefined) updates.lyricsPrompt = lyricsPrompt;

        const updated = await SchedulerModel.update(id, updates);
        console.log(`[Schedulers] ✅ Updated scheduler: ${id}`);

        res.json({ scheduler: updated });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

/**
 * POST /api/schedulers/:id/toggle
 * Activate/deactivate scheduler
 */
router.post('/:id/toggle', async (req, res) => {
    const { id } = req.params;

    try {
        const updated = await SchedulerModel.toggleActive(id);
        console.log(`[Schedulers] Toggled scheduler: ${id} - Active: ${updated.active}`);

        res.json({ scheduler: updated });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

/**
 * DELETE /api/schedulers/:id
 * Delete scheduler
 */
router.delete('/:id', async (req, res) => {
    const { id } = req.params;

    try {
        await SchedulerModel.delete(id);
        console.log(`[Schedulers] ✅ Deleted scheduler: ${id}`);

        res.json({ success: true, message: 'Scheduler deleted' });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

module.exports = router;
